name: Java Pull Request Check

on:
  push:
    branches: [ main ]
    paths:
        - "packages/java/**"

  pull_request:
    branches: [ main ]
    paths:
      - "packages/java/**"    

  workflow_dispatch:

jobs:
  checking-pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      working-directory: ./packages/java
      run: mvn clean install

    - name: Run tests
      working-directory: ./packages/java
      run: mvn test
